### ISSUE TITLE
Operator request: 32 CUSTOM!

### ISSUE THREAD

**Issue by Prem95** [zhenhuaw-me/tflite2onnx#78]
**Note**: Currently, we only accept [TensorFlow Lite builtin operators](https://jackwish.net/tflite/docs/BuiltinOperator.m.html) request.

**What is the TensorFlow Lite operator you need**
(Please attach a tiny TFLite model `*.tflite`, which contains the operator you need ONLY.)

I would need the 32 CUSTOM operator for ONXX model

**What kind of service you are trying to deploy your model?**
I am trying to deploy a face recognition model on an Android device 

**Would you like to contribute the operator?**
No 

**Additional context**

**Comment by Prem95** [comment]
Hi there, any update here?

**Comment by emre84** [comment]
I am getting the same error:
Notimplementederror: Unsupported TFLite OP: 32 CUSTOM!
os:windows
tflite22onnx:0.4.1

Do i have to open an other issue or may i just track the existing one? Is there any planned due date for the implementation?

thanks a lot in advance.

**Comment by emre84** [comment]
any update here?
